### ISSUE TITLE
non-ascii journal titles

### ISSUE THREAD

**Issue by kaplun** [inspirehep/refextract#25] opened 2017-03-30 11:58 UTC
https://sentry.cern.ch/inspire-sentry/inspire-labs/group/820653/

**Comment by michamos** [comment] 2017-03-30 12:02
this is not a `refextract` bug, the default format string was changed to unicode in #16, but `inspire-next` uses a different one that should be fixed as part of inspirehep/inspire-next#2133.

**Comment by michamos** [comment] 2017-03-30 12:06
@chris-asl the problem is here https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/refextract/tasks.py#L90

**Comment by kaplun** [comment] 2017-03-30 12:07
Are you sure? The exception is triggered deep down in refextract code base.

**Comment by michamos** [comment] 2017-03-30 12:10
Yes, the format string gets passed to refextract and consumed deep inside (one of refextract great design decisions).

**Closed** 2017-03-30 12:21 UTC
Labels: bug

**Comment by kaplun** [comment] 2017-03-30 12:22
:scream:
